// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RacMonsters.Server.Data;

#nullable disable

namespace RacMonsters.Server.Migrations
{
    [DbContext(typeof(RacMonstersDbContext))]
    [Migration("20260302170100_Sounds")]
    partial class Sounds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RacMonsters.Server.Data.AbilityEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Accuracy")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsHeal")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTech")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Power")
                        .HasColumnType("int");

                    b.Property<int>("Speed")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Abilities", (string)null);
                });

            modelBuilder.Entity("RacMonsters.Server.Data.BattleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterAId")
                        .HasColumnType("int");

                    b.Property<int>("CharacterBId")
                        .HasColumnType("int");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<int?>("WinningCharacterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CharacterAId");

                    b.HasIndex("CharacterBId");

                    b.HasIndex("SessionId");

                    b.HasIndex("WinningCharacterId");

                    b.ToTable("Battles", (string)null);
                });

            modelBuilder.Entity("RacMonsters.Server.Data.CharacterAbilityEntity", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("AbilityId")
                        .HasColumnType("int");

                    b.HasKey("CharacterId", "AbilityId");

                    b.HasIndex("AbilityId");

                    b.ToTable("CharacterAbilities", (string)null);
                });

            modelBuilder.Entity("RacMonsters.Server.Data.CharacterEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Attack")
                        .HasColumnType("int");

                    b.Property<int>("CurrentHealth")
                        .HasColumnType("int");

                    b.Property<int>("Defense")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MaxHealth")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TechAttack")
                        .HasColumnType("int");

                    b.Property<int>("TechDefense")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Characters", (string)null);
                });

            modelBuilder.Entity("RacMonsters.Server.Data.LeaderboardEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Character")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Leaderboard", (string)null);
                });

            modelBuilder.Entity("RacMonsters.Server.Data.RoundEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BattleId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerAAbilityId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerACharacterId")
                        .HasColumnType("int");

                    b.Property<int?>("PlayerADamage")
                        .HasColumnType("int");

                    b.Property<int?>("PlayerAHealAmount")
                        .HasColumnType("int");

                    b.Property<bool?>("PlayerAHit")
                        .HasColumnType("bit");

                    b.Property<string>("PlayerAResultMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlayerBAbilityId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerBCharacterId")
                        .HasColumnType("int");

                    b.Property<int?>("PlayerBDamage")
                        .HasColumnType("int");

                    b.Property<int?>("PlayerBHealAmount")
                        .HasColumnType("int");

                    b.Property<bool?>("PlayerBHit")
                        .HasColumnType("bit");

                    b.Property<string>("PlayerBResultMessage")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BattleId");

                    b.HasIndex("PlayerAAbilityId");

                    b.HasIndex("PlayerACharacterId");

                    b.HasIndex("PlayerBAbilityId");

                    b.HasIndex("PlayerBCharacterId");

                    b.ToTable("Rounds", (string)null);
                });

            modelBuilder.Entity("RacMonsters.Server.Data.SessionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Sessions", (string)null);
                });

            modelBuilder.Entity("RacMonsters.Server.Data.BattleEntity", b =>
                {
                    b.HasOne("RacMonsters.Server.Data.CharacterEntity", "CharacterA")
                        .WithMany()
                        .HasForeignKey("CharacterAId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RacMonsters.Server.Data.CharacterEntity", "CharacterB")
                        .WithMany()
                        .HasForeignKey("CharacterBId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RacMonsters.Server.Data.SessionEntity", "Session")
                        .WithMany("Battles")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RacMonsters.Server.Data.CharacterEntity", "WinningCharacterEntity")
                        .WithMany()
                        .HasForeignKey("WinningCharacterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CharacterA");

                    b.Navigation("CharacterB");

                    b.Navigation("Session");

                    b.Navigation("WinningCharacterEntity");
                });

            modelBuilder.Entity("RacMonsters.Server.Data.CharacterAbilityEntity", b =>
                {
                    b.HasOne("RacMonsters.Server.Data.AbilityEntity", "Ability")
                        .WithMany("CharacterAbilities")
                        .HasForeignKey("AbilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RacMonsters.Server.Data.CharacterEntity", "Character")
                        .WithMany("CharacterAbilities")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ability");

                    b.Navigation("Character");
                });

            modelBuilder.Entity("RacMonsters.Server.Data.RoundEntity", b =>
                {
                    b.HasOne("RacMonsters.Server.Data.BattleEntity", "Battle")
                        .WithMany("Rounds")
                        .HasForeignKey("BattleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RacMonsters.Server.Data.AbilityEntity", "PlayerAAbility")
                        .WithMany()
                        .HasForeignKey("PlayerAAbilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RacMonsters.Server.Data.CharacterEntity", "PlayerACharacter")
                        .WithMany()
                        .HasForeignKey("PlayerACharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RacMonsters.Server.Data.AbilityEntity", "PlayerBAbility")
                        .WithMany()
                        .HasForeignKey("PlayerBAbilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RacMonsters.Server.Data.CharacterEntity", "PlayerBCharacter")
                        .WithMany()
                        .HasForeignKey("PlayerBCharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Battle");

                    b.Navigation("PlayerAAbility");

                    b.Navigation("PlayerACharacter");

                    b.Navigation("PlayerBAbility");

                    b.Navigation("PlayerBCharacter");
                });

            modelBuilder.Entity("RacMonsters.Server.Data.AbilityEntity", b =>
                {
                    b.Navigation("CharacterAbilities");
                });

            modelBuilder.Entity("RacMonsters.Server.Data.BattleEntity", b =>
                {
                    b.Navigation("Rounds");
                });

            modelBuilder.Entity("RacMonsters.Server.Data.CharacterEntity", b =>
                {
                    b.Navigation("CharacterAbilities");
                });

            modelBuilder.Entity("RacMonsters.Server.Data.SessionEntity", b =>
                {
                    b.Navigation("Battles");
                });
#pragma warning restore 612, 618
        }
    }
}
